### ISSUE TITLE
{{ site.baseurl }} text

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/RCAT#3]
@joewheaton and I noticed that for the picture links in the [R-CAT site](http://rcat.riverscapes.xyz/) we have been able to add images (for example) `![analyzedstreams_web1](/assets/images/analyzedstreams_web1.png)` instead of adding in the `{{ site.baseurl }}` previous to `/assets/images/`.  This has been working great so far, is there any reason we would need to throw the `{{ site.baseurl }}` in front of `/assets/images/` for all the pictures that we don't understand right now? @MattReimer @philipbaileynar 
Thanks for your help.

**Comment by philipbaileynar** [comment]
I think that it's because you are using DNS to point a URL at the site. Without the DNS, the site sits in a subfolder of the URL where the sub folder is the name of the repo.

So we have a repo called `CHaMPAutomation` and the home page of this GitHub site is:

`https://riverscapes.github.io/CHaMPAutomation/`

Without the `{{ site.baseurl }}` the links would just start at ``https://riverscapes.github.io`. The base URL includes the `CHaMPAutomation` folder.

Once you use a DNS though, the URL points right at the folder where the site lives and the subfolder is not visible.

**Comment by lhaycock** [comment]
@philipbaileynar  Thanks for the explanation.  I will keep that in mind for the future sites I am migrating.
