### ISSUE TITLE
RCAT header

### ISSUE THREAD

**Issue by lhaycock** [Riverscapes/RCAT#5]
@joewheaton ,
I noticed in the header of the RCAT page there are some buttons:
![header](https://user-images.githubusercontent.com/30474526/38155888-8352fb74-3437-11e8-8ec5-e80201087f6e.png)

I do not know how these got added, and they do not work.  Do you have any direction for me to get these fixed/updated?
Thanks,

**Comment by joewheaton** [comment]
Good catch @lhaycock. This is not an issue with RCAT git pages or the header specifically, but simply because I have not yet hooked up the http://riverscapes.xyz domain yet. In the interim, these are temporarily at http://riverscapes.weebly.com, but I need to finish editing the site. This should be resolved by June. @banderson1618 asked a similar question recently...
